CREATE TABLE users(
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(256) NOT NULL,
    password VARCHAR(256) NOT NULL,
    token VARCHAR(256)
);

ALTER TABLE users
ADD CONSTRAINT email_unique UNIQUE (email);

